name: Quick Test
on: push
jobs:
  quick-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: eifinger/setup-rye@v4
      - run: rye sync
      - run: rye run lint
      - run: rye run typecheck
      - run: rye run test tests/unit/ --tb=short
