name: Quick Test
on: push
jobs:
  quick-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential clang
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: eifinger/setup-rye@v4
      - run: rm -rf .venv  # Clean any existing venv
      - run: rye sync
      - run: rye run lint
      - run: rye run typecheck
      - run: rye run test tests/unit/ --tb=short
